### ISSUE TITLE
Super Bunny Cave access

### ISSUE THREAD

**Issue by miketrethewey** [Orphis/alttp_entrance_randomizer_tracker#1]
Super Bunny Cave should be accessible from both DW East DM Upper Exit & DW Twin Cave Left, bidirectional. It only let you link from top to bottom and not from bottom to top.

**Comment by miketrethewey** [comment]
Vandalite helped and I've got a fix in Pull Request #2 .

**Comment by Orphis** [comment]
Oh that's right, thanks for finding this issue!
Let me know if you find more like these, I wouldn't be surprised much :)
